In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('Weather Data.csv')

In [3]:
df.head(5)

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,01-01-2012 00:00,-1.3,-3.5,18,9,25.0,98.67,Clear
1,01-01-2012 01:00,7.4,2.8,20,24,24.1,99.37,Rain
2,01-01-2012 02:00,15.7,13.4,21,26,25.0,99.84,Cloudy
3,01-01-2012 03:00,4.9,-2.6,27,15,24.1,100.94,Mainly Clear
4,01-01-2012 04:00,-13.4,-19.7,30,4,25.0,102.32,Mostly Cloudy

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date/Time         8784 non-null   object
 1   Temp_C            8784 non-null   float64
 2   Dew Point Temp_C  8784 non-null   float64
 3   Rel Hum_%         8784 non-null   int64
 4   Wind Speed_km/h   8784 non-null   int64
 5   Visibility_km     8784 non-null   float64
 6   Press_kPa         8784 non-null   float64
 7   Weather           8784 non-null   object
dtypes: float64(4), int64(2), object(2)
memory usage: 549.1+ KB

In [5]:
df['Wind Speed_km/h'].unique()

array([ 9, 24, 26, 15,  4,  0, 19, 17, 11, 22, 35, 13, 20,  6,  7, 30, 32,
       41, 39, 28, 44, 33, 37, 52, 46,  2, 50, 48, 57, 63, 43, 83, 70, 54],
      dtype=int64)

In [6]:
df['Weather'].value_counts().Clear

1326

In [7]:
df['Wind Speed_km/h'].value_counts()[4]

474

In [8]:
df.isnull().sum()

Date/Time           0
Temp_C              0
Dew Point Temp_C    0
Rel Hum_%           0
Wind Speed_km/h     0
Visibility_km       0
Press_kPa           0
Weather             0
dtype: int64

In [9]:
df.rename(columns = {'Weather':'Weather Condition'} , inplace = True)

In [10]:
df.head()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
0,01-01-2012 00:00,-1.3,-3.5,18,9,25.0,98.67,Clear
1,01-01-2012 01:00,7.4,2.8,20,24,24.1,99.37,Rain
2,01-01-2012 02:00,15.7,13.4,21,26,25.0,99.84,Cloudy
3,01-01-2012 03:00,4.9,-2.6,27,15,24.1,100.94,Mainly Clear
4,01-01-2012 04:00,-13.4,-19.7,30,4,25.0,102.32,Mostly Cloudy

In [11]:
df['Visibility_km'].mean()

27.664446721311478

In [12]:
df['Press_kPa'].std()

0.8440047459486459

In [13]:
df['Rel Hum_%'].var()

286.2485501985015

In [14]:
df[df['Weather Condition'] == 'Snow']

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
11,01-01-2012 11:00,-6.2,-9.6,37,35,4.8,101.56,Snow
70,03-01-2012 22:00,-4.0,-6.6,62,22,16.1,100.48,Snow
73,04-01-2012 01:00,2.3,-3.4,64,35,25.0,103.43,Snow
105,05-01-2012 09:00,-1.8,-4.2,73,15,6.4,101.28,Snow
112,05-01-2012 16:00,1.7,-0.3,75,6,9.7,101.47,Snow
...,...,...,...,...,...,...,...,...
8573,9/22/2012 13:00,-6.0,-10.2,82,19,16.1,101.71,Snow
8650,9/25/2012 18:00,-4.6,-6.6,52,4,12.9,100.48,Snow
8671,9/26/2012 15:00,-5.9,-10.5,60,13,16.1,101.01,Snow
8713,9/28/2012 1:00,-5.2,-7.8,72,33,4.0,101.33,Snow
8734,9/28/2012 8:00,0.7,-1.2,79,30,8.0,101.22,Snow

In [15]:
df[(df['Wind Speed_km/h'] > 24) & (df['Visibility_km'] == 25)]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
2,01-01-2012 02:00,15.7,13.4,21,26,25.0,99.84,Cloudy
73,04-01-2012 01:00,2.3,-3.4,64,35,25.0,103.43,Snow
126,06-01-2012 06:00,10.0,5.4,77,39,25.0,101.30,Cloudy
158,07-01-2012 14:00,1.9,-2.1,87,26,25.0,100.87,"Rain,Snow Grains"
184,08-01-2012 16:00,14.2,9.2,35,44,25.0,99.49,Mostly Cloudy
...,...,...,...,...,...,...,...,...
8707,9/27/2012 5:00,-1.0,-6.0,70,33,25.0,98.56,Mostly Cloudy
8714,9/28/2012 10:00,2.6,0.3,72,26,25.0,101.60,Rain
8738,9/29/2012 10:00,22.8,12.3,80,28,25.0,101.60,Mostly Cloudy
8745,9/29/2012 17:00,-10.3,-12.9,82,28,25.0,102.16,Cloudy
8776,9/30/2012 23:00,19.2,13.2,93,43,25.0,101.60,Mainly Clear

In [16]:
df[df['Weather Condition'] == 'Fog']

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
13,01-01-2012 13:00,9.5,7.8,40,13,6.4,100.90,Fog
53,03-01-2012 05:00,-3.6,-4.3,57,7,9.7,101.32,Fog
136,06-01-2012 16:00,14.8,13.5,80,19,9.7,100.86,Fog
197,09-01-2012 05:00,2.1,0.7,43,11,8.0,101.44,Fog
278,12-01-2012 14:00,1.2,0.6,70,13,6.4,103.22,Fog
...,...,...,...,...,...,...,...,...
8475,9/18/2012 11:00,6.2,5.4,56,7,4.8,102.03,Fog
8511,9/19/2012 22:00,15.7,15.4,66,7,8.0,101.93,Fog
8518,9/19/2012 8:00,-2.9,-4.5,68,6,6.4,100.41,Fog
8537,9/20/2012 3:00,-0.5,-2.1,74,7,4.0,100.81,Fog
8771,9/30/2012 19:00,12.8,12.2,91,19,4.8,100.60,Fog

In [17]:
df[(df['Weather Condition'] == 'Clear') | (df['Visibility_km'] > 40)]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
0,01-01-2012 00:00,-1.3,-3.5,18,9,25.0,98.67,Clear
9,01-01-2012 09:00,20.0,3.8,35,17,48.3,100.11,Clear
16,01-01-2012 16:00,23.8,17.6,42,9,25.0,100.52,Clear
17,01-01-2012 17:00,-6.8,-9.8,42,20,48.3,100.76,Mainly Clear
18,01-01-2012 18:00,2.3,-2.4,42,6,48.3,101.05,Cloudy
...,...,...,...,...,...,...,...,...
8774,9/30/2012 21:00,23.0,14.7,92,13,48.3,101.93,Mostly Cloudy
8777,9/30/2012 3:00,9.3,5.8,95,9,48.3,101.25,Mainly Clear
8779,9/30/2012 5:00,1.4,-3.7,97,22,48.3,100.16,Cloudy
8780,9/30/2012 6:00,-4.6,-9.5,98,11,48.3,101.46,Mostly Cloudy
8781,9/30/2012 7:00,1.5,-6.3,99,30,24.1,101.48,Clear

In [18]:
df[((df['Weather Condition'] == 'Clear') & (df['Rel Hum_%'] > 50)) | (df['Visibility_km'] > 40)]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
9,01-01-2012 09:00,20.0,3.8,35,17,48.3,100.11,Clear
17,01-01-2012 17:00,-6.8,-9.8,42,20,48.3,100.76,Mainly Clear
18,01-01-2012 18:00,2.3,-2.4,42,6,48.3,101.05,Cloudy
19,01-01-2012 19:00,-12.7,-17.2,43,17,48.3,101.16,Clear
23,01-01-2012 23:00,29.5,16.8,45,4,48.3,101.07,Mainly Clear
...,...,...,...,...,...,...,...,...
8774,9/30/2012 21:00,23.0,14.7,92,13,48.3,101.93,Mostly Cloudy
8777,9/30/2012 3:00,9.3,5.8,95,9,48.3,101.25,Mainly Clear
8779,9/30/2012 5:00,1.4,-3.7,97,22,48.3,100.16,Cloudy
8780,9/30/2012 6:00,-4.6,-9.5,98,11,48.3,101.46,Mostly Cloudy
8781,9/30/2012 7:00,1.5,-6.3,99,30,24.1,101.48,Clear

In [19]:
df.groupby('Weather Condition').mean(numeric_only = True).head()

,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa
Weather Condition,,,,,,
Clear,6.825716,0.089367,67.127451,10.557315,30.153243,101.084495
Cloudy,7.970544,2.375810,67.349537,16.127315,26.625752,101.056852
Drizzle,7.353659,5.504878,69.048780,16.097561,17.931707,101.099268
"Drizzle,Fog",8.067500,7.033750,70.062500,11.862500,5.257500,100.820750
"Drizzle,Ice Pellets,Fog",0.400000,-0.700000,52.000000,20.000000,4.000000,99.440000

In [31]:
df.groupby('Weather Condition').agg(['min','max']).head()

                                Date/Time                  Temp_C        \
                                      min              max    min   max
Weather Condition
Clear                    01-01-2012 00:00   9/30/2012 7:00  -23.3  32.8
Cloudy                   01-01-2012 02:00   9/30/2012 8:00  -21.4  30.5
Drizzle                  01-06-2012 08:00  9/15/2012 22:00    1.1  18.8
Drizzle,Fog              01-04-2012 01:00  9/19/2012 15:00    0.0  19.9
Drizzle,Ice Pellets,Fog    7/24/2012 5:00   7/24/2012 5:00    0.4   0.4

                        Dew Point Temp_C       Rel Hum_%      Wind Speed_km/h  \
                                     min   max       min  max             min
Weather Condition
Clear                              -28.5  20.4        18  100               0
Cloudy                             -26.8  22.6        20  100               0
Drizzle                             -0.2  17.7        37   97               0
Drizzle,Fog                         -1.6  19.1        38   98               0
Drizzle,Ice Pellets,Fog             -0.7  -0.7        52   52              20

                            Visibility_km       Press_kPa
                        max           min   max       min     max
Weather Condition
Clear                    33          11.3  48.3     97.75  103.63
Cloudy                   54          11.3  48.3     97.52  103.52
Drizzle                  30           6.4  25.0     98.29  103.58
Drizzle,Fog              28           1.0   9.7     98.32  103.56
Drizzle,Ice Pellets,Fog  20           4.0   4.0     99.44   99.44

In [28]:
df.groupby('Weather Condition').max().head()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa
Weather Condition,,,,,,,
Clear,9/30/2012 7:00,32.8,20.4,100,33,48.3,103.63
Cloudy,9/30/2012 8:00,30.5,22.6,100,54,48.3,103.52
Drizzle,9/15/2012 22:00,18.8,17.7,97,30,25.0,103.58
"Drizzle,Fog",9/19/2012 15:00,19.9,19.1,98,28,9.7,103.56
"Drizzle,Ice Pellets,Fog",7/24/2012 5:00,0.4,-0.7,52,20,4.0,99.44